var floatUserage, floatDays, floatMonths, floatAge, intWeeks, intFortnights;
     floatUserage = parseFloat(prompt("How old are you?"));
     floatDays = parseFloat(floatUserage*365.25);
     floatMonths = parseFloat(floatUserage*12);
     intWeeks = parseInt(floatDays / 7);
     intFortnights = parseInt(floatDays / 14);
     alert("Your age in fort nights is: " intFortnights);
     alert("Your age in weeks is: " intWeeks);
     alert("Your age in months is: " floatMonths);
     alert("Your age is in days: " + floatDays;